"""
Seed Legal Knowledge Base
==========================
Builds a curated legal_knowledge collection with ~200 high-quality chunks
covering GDPR, BGB, NDA law, DPA requirements, Schrems II, employment law.
No external downloads — uses embedded authoritative legal text.
~$0.01 in embedding cost.
"""
import os, sys
from pathlib import Path
from dotenv import load_dotenv
load_dotenv()

LEGAL_CHUNKS = [
    # ── GDPR ─────────────────────────────────────────────────────────────
    {"source": "GDPR Art.5", "text": "Article 5 GDPR — Principles relating to processing of personal data: Personal data shall be (a) processed lawfully, fairly and in a transparent manner in relation to the data subject ('lawfulness, fairness and transparency'); (b) collected for specified, explicit and legitimate purposes and not further processed in a manner that is incompatible with those purposes ('purpose limitation'); (c) adequate, relevant and limited to what is necessary ('data minimisation'); (d) accurate and, where necessary, kept up to date ('accuracy'); (e) kept in a form which permits identification of data subjects for no longer than is necessary ('storage limitation'); (f) processed in a manner that ensures appropriate security ('integrity and confidentiality')."},
    {"source": "GDPR Art.6", "text": "Article 6 GDPR — Lawfulness of processing: Processing shall be lawful only if and to the extent that at least one of the following applies: (a) the data subject has given consent; (b) processing is necessary for the performance of a contract; (c) processing is necessary for compliance with a legal obligation; (d) processing is necessary in order to protect the vital interests of the data subject; (e) processing is necessary for the performance of a task carried out in the public interest; (f) processing is necessary for the purposes of the legitimate interests pursued by the controller."},
    {"source": "GDPR Art.7", "text": "Article 7 GDPR — Conditions for consent: Where processing is based on consent, the controller shall be able to demonstrate that the data subject has consented. If the data subject's consent is given in the context of a written declaration which also concerns other matters, the request for consent shall be presented in a manner which is clearly distinguishable from the other matters. The data subject shall have the right to withdraw his or her consent at any time. The withdrawal of consent shall not affect the lawfulness of processing based on consent before its withdrawal."},
    {"source": "GDPR Art.13", "text": "Article 13 GDPR — Information to be provided where personal data are collected from the data subject: The controller shall provide the data subject with information including: identity and contact details of the controller; contact details of the data protection officer; the purposes and legal basis for processing; the recipients or categories of recipients; retention periods; the right to access, rectification, erasure, restriction, portability and to object; the right to withdraw consent; the right to lodge a complaint with a supervisory authority."},
    {"source": "GDPR Art.17", "text": "Article 17 GDPR — Right to erasure ('right to be forgotten'): The data subject shall have the right to obtain from the controller the erasure of personal data without undue delay where: the personal data are no longer necessary for the purposes for which they were collected; the data subject withdraws consent and there is no other legal ground; the data subject objects to the processing; the personal data have been unlawfully processed; erasure is required for compliance with a legal obligation. The controller shall take reasonable steps to inform other controllers processing the data."},
    {"source": "GDPR Art.20", "text": "Article 20 GDPR — Right to data portability: The data subject shall have the right to receive the personal data concerning him or her in a structured, commonly used and machine-readable format and have the right to transmit those data to another controller without hindrance, where processing is based on consent or on a contract and the processing is carried out by automated means."},
    {"source": "GDPR Art.28", "text": "Article 28 GDPR — Processor obligations: Where processing is to be carried out on behalf of a controller, the controller shall use only processors providing sufficient guarantees to implement appropriate technical and organisational measures. Processing by a processor shall be governed by a contract (Data Processing Agreement) setting out the subject-matter, duration, nature and purpose of the processing, the type of personal data and categories of data subjects, and the obligations and rights of the controller. The processor shall process personal data only on documented instructions from the controller. The processor shall ensure that persons authorised to process have committed themselves to confidentiality. The processor shall implement all measures required pursuant to Article 32 (security). The processor shall assist the controller in ensuring compliance with Articles 32-36."},
    {"source": "GDPR Art.32", "text": "Article 32 GDPR — Security of processing: Taking into account the state of the art, the costs of implementation and the nature, scope, context and purposes of processing as well as the risk of varying likelihood and severity for the rights and freedoms of natural persons, the controller and processor shall implement appropriate technical and organisational measures to ensure a level of security appropriate to the risk, including: (a) the pseudonymisation and encryption of personal data; (b) the ability to ensure the ongoing confidentiality, integrity, availability and resilience of processing systems and services; (c) the ability to restore the availability and access to personal data in a timely manner in the event of a physical or technical incident; (d) a process for regularly testing, assessing and evaluating the effectiveness of technical and organisational measures."},
    {"source": "GDPR Art.33", "text": "Article 33 GDPR — Notification of a personal data breach to the supervisory authority: In the case of a personal data breach, the controller shall without undue delay and, where feasible, not later than 72 hours after having become aware of it, notify the personal data breach to the supervisory authority. The notification shall at least: (a) describe the nature of the breach including categories and approximate number of data subjects concerned and personal data records concerned; (b) communicate the name and contact details of the data protection officer; (c) describe the likely consequences of the breach; (d) describe the measures taken or proposed to address the breach."},
    {"source": "GDPR Art.35", "text": "Article 35 GDPR — Data protection impact assessment (DPIA): Where a type of processing is likely to result in a high risk to the rights and freedoms of natural persons, the controller shall carry out an assessment of the impact of the envisaged processing operations on the protection of personal data. A DPIA is required in particular in the case of: systematic and extensive evaluation of personal aspects; processing on a large scale of special categories of data; systematic monitoring of a publicly accessible area on a large scale."},
    {"source": "GDPR Art.44", "text": "Article 44 GDPR — General principle for transfers: Any transfer of personal data which are undergoing processing or are intended for processing after transfer to a third country or to an international organisation shall take place only if the conditions laid down in Chapter V are complied with. All provisions in Chapter V shall be applied in order to ensure that the level of protection of natural persons guaranteed by this Regulation is not undermined."},
    {"source": "GDPR Art.46", "text": "Article 46 GDPR — Transfers subject to appropriate safeguards: In the absence of a decision pursuant to Article 45(3), a controller or processor may transfer personal data to a third country only if the controller or processor has provided appropriate safeguards, including: (a) a legally binding and enforceable instrument between public authorities; (b) binding corporate rules; (c) standard data protection clauses (SCCs) adopted by the Commission; (d) approved codes of conduct; (e) approved certification mechanisms. Data subjects must have enforceable rights and effective legal remedies."},
    {"source": "GDPR Art.83", "text": "Article 83 GDPR — General conditions for imposing administrative fines: Infringements of the following provisions shall be subject to administrative fines up to 20,000,000 EUR, or in the case of an undertaking, up to 4% of the total worldwide annual turnover of the preceding financial year, whichever is higher: the basic principles for processing including conditions for consent (Articles 5, 6, 7 and 9); the data subjects' rights (Articles 12-22); the transfers of personal data to a recipient in a third country (Articles 44-49)."},

    # ── Schrems II / Transfer Mechanisms ─────────────────────────────────
    {"source": "Schrems II (C-311/18)", "text": "Schrems II judgment (CJEU C-311/18, 16 July 2020): The Court of Justice invalidated the EU-US Privacy Shield. Standard Contractual Clauses (SCCs) remain valid but require a case-by-case transfer impact assessment (TIA). Controllers and processors must verify whether the law and practices of the destination country ensure an essentially equivalent level of protection. Where US surveillance laws (e.g. FISA 702, Executive Order 12333) may apply to the transferred data, additional safeguards are required. Transfers without adequate protection expose parties to GDPR Art.83 fines up to 4% of global turnover."},
    {"source": "Schrems II — SCCs", "text": "Post-Schrems II Standard Contractual Clauses (SCCs): The European Commission adopted new SCCs (June 2021) with four modules: Module 1 (Controller to Controller), Module 2 (Controller to Processor), Module 3 (Processor to Controller), Module 4 (Processor to Processor). Each module requires a Transfer Impact Assessment (TIA). The TIA must assess: (1) purpose and legal basis of transfer; (2) laws of the recipient country affecting data protection; (3) technical, contractual and organisational safeguards. If the TIA shows inadequate protection, the transfer must be suspended."},
    {"source": "EU-US Data Privacy Framework", "text": "EU-US Data Privacy Framework (DPF, adopted July 2023): Replaces Privacy Shield following Schrems II. US companies can self-certify adherence to DPF principles. Provides EU individuals with redress rights including a new Data Protection Review Court (DPRC). However, the DPF may face legal challenge (Schrems III). Companies relying solely on DPF should maintain SCCs as backup safeguard. German DPA (BfDI) has expressed concerns about adequacy of US surveillance law limitations under the DPF."},

    # ── DPA / Art.28 Contract Requirements ───────────────────────────────
    {"source": "Art.28 DPA Requirements", "text": "Data Processing Agreement (DPA) mandatory clauses under GDPR Art.28: (1) Subject-matter and duration of processing; (2) Nature and purpose of processing; (3) Type of personal data; (4) Categories of data subjects; (5) Processor processes data only on documented instructions; (6) Confidentiality obligations on all authorised persons; (7) Implementation of Art.32 security measures; (8) Subprocessor engagement requires prior written controller authorisation; (9) Assistance to controller for data subject rights requests; (10) Deletion or return of all personal data at end of service; (11) Provision of all information necessary to demonstrate compliance; (12) Allowing and contributing to audits. A DPA without these clauses is non-compliant and creates liability for both parties."},
    {"source": "Art.28 Subprocessor Chain", "text": "Subprocessor obligations under GDPR Art.28(2)-(4): The processor shall not engage another processor (subprocessor) without prior specific or general written authorisation of the controller. Where general written authorisation is given, the processor must inform the controller of intended changes and give the controller opportunity to object. Where a processor engages a subprocessor, the same data protection obligations as set out in the contract between controller and processor shall be imposed on the subprocessor by way of a contract. If a subprocessor fails to fulfil its data protection obligations, the initial processor shall remain fully liable to the controller."},

    # ── BGB (German Civil Code) ───────────────────────────────────────────
    {"source": "BGB §74 — Non-Compete", "text": "§74 BGB (German Civil Code) — Non-competition clause: A non-competition clause between an employer and employee is only valid if: (1) it is agreed in writing; (2) it applies to the employee's activities; (3) the employer has a legitimate business interest; (4) the maximum duration does not exceed 2 years after termination. The employer must pay compensation of at least 50% of the last contractual remuneration (Karenzentschädigung) for the duration of the restriction. Non-compete clauses exceeding 2 years are void. Clauses without compensation are non-binding (the employee can choose to comply or ignore them)."},
    {"source": "BGB §305 — Standard Terms", "text": "§305 BGB — Incorporation of standard business terms (AGB): Standard terms are provisions pre-formulated for multiple contracts. They become part of a contract only if the party using them expressly drew the other party's attention to them before contracting and gave the other party a reasonable opportunity to take note of their content. Standard terms do not apply if they were not reasonably accessible. In B2C contracts, statutory rules for unfair terms under §§307-309 BGB apply and can render clauses void."},
    {"source": "BGB §307 — Unfair Terms", "text": "§307 BGB — Content review of standard terms: Provisions in standard terms are ineffective if, contrary to the requirement of good faith, they unreasonably disadvantage the other party. An unreasonable disadvantage is in particular present when a provision: (1) is incompatible with essential principles of the statutory rule from which it deviates; (2) restricts essential rights or duties inherent in the nature of the contract in a way that jeopardises the attainment of the contract's purpose. In case of doubt, standard terms are interpreted against the party that introduced them (contra proferentem)."},
    {"source": "BGB §309 — Void Clauses", "text": "§309 BGB — Clauses that are always void in standard terms (B2C): Clauses that are always void include: (1) limiting liability for personal injury caused by negligence; (2) clauses requiring payment without performance; (3) clauses limiting statutory warranty periods to less than one year for new goods; (4) clauses excluding or limiting the right to withhold payment; (5) automatic renewal clauses with renewal periods exceeding one year; (6) clauses allowing unilateral price increases within 4 months of contract conclusion. These limitations cannot be contracted away."},
    {"source": "BGB §622 — Employment Notice", "text": "§622 BGB — Notice periods for employment contracts: The statutory minimum notice period for employees is 4 weeks to the 15th or end of the month. For employers, notice periods increase with length of employment: 1 month (2+ years service); 2 months (5+ years); 3 months (8+ years); 4 months (10+ years); 5 months (12+ years); 6 months (15+ years); 7 months (20+ years). Notice periods shorter than the statutory minimum are void. During probationary period (max 6 months), notice can be given with 2 weeks' notice. These are minimum standards — longer periods can be agreed contractually."},
    {"source": "BGB §611a — Employment Contract", "text": "§611a BGB — Employment contract: By an employment contract, the employee undertakes to perform work in personal dependence, following the instructions of the employer regarding content, execution, time, duration and place of work. Whoever is dependent on instructions and therefore personally dependent in performing work for another is an employee. The actual performance of the contract shall be taken into account; the name or form the parties have given to the contract shall not be decisive. Misclassification of employees as freelancers (Scheinselbständigkeit) carries significant legal and tax penalties."},

    # ── NDA / Confidentiality Law ─────────────────────────────────────────
    {"source": "NDA — German Law", "text": "Non-Disclosure Agreements under German law: NDAs are governed primarily by BGB contract law. Key requirements for enforceability: (1) Clear definition of confidential information — overly broad definitions may be unenforceable; (2) Reasonable duration — perpetual NDAs are generally enforceable for trade secrets under GeschGehG (Trade Secrets Act), but courts scrutinise post-termination obligations; (3) Consideration — German law does not require separate consideration but the NDA must be part of a broader contractual relationship or have legitimate business purpose; (4) Non-compete vs confidentiality — if an NDA effectively restricts competition, BGB §74 compensation rules may apply; (5) Employee NDAs cannot prevent whistleblowing under HinSchG."},
    {"source": "GeschGehG — Trade Secrets", "text": "Gesetz zum Schutz von Geschäftsgeheimnissen (GeschGehG) — German Trade Secrets Act (implementing EU Directive 2016/943): A trade secret is information that is secret, has commercial value because of its secrecy, and has been subject to reasonable steps to keep it secret. Protection requires active secrecy measures — companies must implement confidentiality agreements, access restrictions and information classification. Reverse engineering is generally permitted unless contractually excluded. Whistleblowing, journalism and public interest disclosures are protected. Remedies include injunctions, damages and destruction of infringing products."},

    # ── Liability Clauses ─────────────────────────────────────────────────
    {"source": "Liability — German Contract Law", "text": "Liability limitations in German contract law: Under BGB §276, liability can be limited by contract for ordinary negligence (einfache Fahrlässigkeit) but not for gross negligence (grobe Fahrlässigkeit) or intentional misconduct (Vorsatz). Liability for personal injury cannot be excluded or limited. Under §309 No.7 BGB (standard terms), clauses excluding liability for personal injury caused by negligence in consumer contracts are always void. In B2B contracts, liability caps are generally enforceable if not unreasonably low relative to the contract value. A liability cap below 100% of annual contract value is often scrutinised. Mutual liability caps are generally more enforceable than unilateral ones."},

    # ── IP Assignment ─────────────────────────────────────────────────────
    {"source": "IP Assignment — German Law", "text": "IP assignment in German law: Under German copyright law (UrhG §43), works created by employees in the course of employment are generally owned by the employer if the creation falls within the scope of employment duties. However, moral rights (Urheberpersönlichkeitsrechte) cannot be transferred — only exploitation rights (Nutzungsrechte) can be assigned. For software, §69b UrhG provides that economic rights vest in the employer automatically for software created by employees in the exercise of duties. Freelancers retain copyright by default — explicit written assignment is required. Patent rights under ArbnErfG — employees must notify employer of inventions made in connection with employment; employer can claim the invention within 4 months."},

    # ── Limitation of Actions ─────────────────────────────────────────────
    {"source": "BGB §195 — Limitation Period", "text": "§195 BGB — Regular limitation period: The regular limitation period is 3 years. The period begins at the end of the year in which the claim arose and the obligee obtained knowledge of the circumstances giving rise to the claim. Special limitation periods apply to: purchase contracts (2 years for defect claims from delivery); land charges (10 years); title to real property (30 years). Limitation periods can be suspended (Hemmung) by negotiations, legal proceedings, or force majeure. Contractual shortening of limitation periods below 1 year for B2C contracts is void under §309 No.8 BGB."},

    # ── CUAD-style Clause Examples ────────────────────────────────────────
    {"source": "Clause — Change of Control", "text": "Change of Control clause — standard provision: Either party may terminate this Agreement upon written notice if the other party undergoes a Change of Control. 'Change of Control' means any transaction or series of transactions whereby any person or entity acquires beneficial ownership of 50% or more of the voting shares of a party, or any merger, acquisition or sale of all or substantially all assets of a party. Notice of termination must be given within 90 days of the Change of Control becoming effective. This provision protects parties from being bound to agreements with unknown counterparties following M&A activity."},
    {"source": "Clause — Governing Law & Jurisdiction", "text": "Governing Law and Jurisdiction — standard DPA clause: This Agreement shall be governed by and construed in accordance with the laws of Germany, excluding its conflict of law provisions. The parties irrevocably submit to the exclusive jurisdiction of the courts of [Munich/Frankfurt/Berlin] for resolution of any disputes arising out of or in connection with this Agreement. For data protection disputes, the competent supervisory authority is [Bayerisches Landesamt für Datenschutzaufsicht / BayLDA / Hamburg DPA] depending on the controller's place of establishment. EU-based disputes regarding GDPR compliance may be escalated to the lead supervisory authority under the one-stop-shop mechanism."},
    {"source": "Clause — Indemnification", "text": "Indemnification clause — standard provision: Each party ('Indemnifying Party') shall indemnify, defend and hold harmless the other party and its officers, directors, employees and agents from and against any claims, damages, losses, costs and expenses (including reasonable legal fees) arising out of or relating to: (a) the Indemnifying Party's breach of this Agreement; (b) the Indemnifying Party's negligence or wilful misconduct; (c) infringement of third-party intellectual property rights caused by the Indemnifying Party's materials. The indemnified party must: (i) promptly notify the indemnifying party of any claim; (ii) give the indemnifying party sole control of the defence; (iii) cooperate reasonably in the defence."},
    {"source": "Clause — Force Majeure", "text": "Force Majeure clause: Neither party shall be liable for delays or failures in performance resulting from causes beyond that party's reasonable control, including acts of God, war, terrorism, riots, embargoes, acts of civil or military authorities, fire, floods, accidents, pandemics, network infrastructure failures, or strikes. The affected party must: (1) promptly notify the other party in writing within 5 business days; (2) use reasonable efforts to mitigate the impact; (3) resume performance as soon as reasonably practicable. If a force majeure event continues for more than 90 days, either party may terminate the Agreement without liability upon 30 days' written notice."},
    {"source": "Clause — Limitation of Liability", "text": "Limitation of Liability — standard commercial clause: IN NO EVENT SHALL EITHER PARTY BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, CONSEQUENTIAL OR PUNITIVE DAMAGES, OR DAMAGES FOR LOSS OF PROFITS, REVENUE, DATA OR GOODWILL, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. EXCEPT FOR BREACHES OF CONFIDENTIALITY, IP OWNERSHIP OR INDEMNIFICATION OBLIGATIONS, EACH PARTY'S TOTAL CUMULATIVE LIABILITY ARISING OUT OF OR RELATED TO THIS AGREEMENT SHALL NOT EXCEED THE TOTAL AMOUNTS PAID OR PAYABLE BY CUSTOMER IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM. Note: Under German law, liability for gross negligence and personal injury cannot be capped."},
    {"source": "Clause — Automatic Renewal", "text": "Automatic Renewal clause: This Agreement shall automatically renew for successive periods equal to the initial term unless either party provides written notice of non-renewal at least [30/60/90] days prior to the end of the then-current term. Risk: Under BGB §309 No.9, automatic renewal clauses in standard terms that renew for periods exceeding one year are void in B2C contracts. In B2B contracts, renewal periods up to 2 years are generally enforceable but may be challenged under §307 BGB if the notice period is unreasonably short. Best practice: provide at least 30 days notice period and limit renewal to 1-year increments."},
    {"source": "Clause — Entire Agreement / Integration", "text": "Entire Agreement clause: This Agreement, together with all Schedules and Exhibits attached hereto, constitutes the entire agreement between the parties with respect to the subject matter hereof and supersedes all prior and contemporaneous agreements, representations, warranties and understandings, whether written or oral, relating to the subject matter. No amendment or modification of this Agreement shall be effective unless made in writing and signed by authorised representatives of both parties. Under German law (BGB §305b), individually negotiated terms (Individualvereinbarungen) take precedence over standard terms even if the standard terms contain a merger clause."},

    # ── Manufacturing / Supply Chain ──────────────────────────────────────
    {"source": "BGB §434 — Defects in Goods", "text": "§434 BGB — Material defect (Sachmangel): A thing is free from material defects if, at the time the risk passes to the buyer, it has the agreed quality. In the absence of agreement, the thing is free from material defects if it is suitable for the contractually presupposed use, or if it is suitable for the ordinary use and has a quality which is usual in things of the same kind. The seller is also liable for defects he fraudulently concealed. In B2B supply agreements, parties may contractually restrict or expand this statutory warranty. However, under §309 No.8b BGB, in standard terms for new goods, the warranty period cannot be reduced below 1 year. The buyer must inspect the goods promptly upon delivery and give notice of defects without undue delay (§377 HGB)."},
    {"source": "BGB §437 — Remedies for Defects", "text": "§437 BGB — Rights of buyer in case of defect: If the goods are defective, the buyer may: (1) demand subsequent performance (Nacherfüllung) — either repair or replacement; (2) withdraw from the contract or reduce the purchase price; (3) claim damages or reimbursement of expenses. The seller has the right to attempt subsequent performance twice before the buyer can withdraw or claim damages. In manufacturing supply agreements, parties often contractually define defect categories (minor defects, major defects, critical defects) with different remedies per category. Recall costs and production line shutdown damages are typically only recoverable if explicitly addressed in the contract."},
    {"source": "EU Product Liability Directive", "text": "EU Product Liability Directive (85/374/EEC, revised 2024): A producer is liable for damage caused by a defective product. A product is defective if it does not provide the safety which a person is entitled to expect. The producer includes: the manufacturer of a finished product; the producer of a raw material; the manufacturer of a component part; any person who puts their name or trade mark on the product; any importer into the EU. Liability cannot be excluded or limited by contract with the injured person. Damages cover personal injury, death, and property damage (above €500 threshold). The 2024 revision expands liability to software, AI systems and digital manufacturing. Limitation period: 3 years from discovery; long-stop: 10 years from product being put into circulation (new Directive extends to 25 years for latent damage)."},
    {"source": "LkSG — Supply Chain Due Diligence Act", "text": "Lieferkettensorgfaltspflichtengesetz (LkSG) — German Supply Chain Due Diligence Act (effective 1 January 2023 for companies with 3,000+ employees; 1 January 2024 for 1,000+ employees): Requires companies to conduct risk analysis and implement preventive and remedial measures in their supply chain for: (1) human rights risks (child labour, forced labour, discrimination, freedom of association); (2) environmental risks (mercury, persistent organic pollutants, hazardous waste). Companies must: establish a risk management system; conduct annual risk analyses; implement preventive measures; establish a complaints mechanism; document and report annually to BAFA. Non-compliance: fines up to 2% of global annual turnover; exclusion from public procurement for up to 3 years. Supply agreements should include LkSG compliance clauses and audit rights."},
    {"source": "Manufacturing — Delivery & Acceptance", "text": "Delivery and acceptance clauses in manufacturing supply agreements: Key provisions: (1) Incoterms (2020) govern risk transfer and cost allocation for international shipments — EXW (Ex Works), FCA, FOB, CIF, DDP are most common; (2) Acceptance testing procedure — defines how goods are inspected; (3) Deemed acceptance — if buyer does not reject within X days, goods are deemed accepted; (4) Delivery delay penalties — liquidated damages (Vertragsstrafe) must be reasonable; under BGB §343, courts may reduce disproportionate contractual penalties; (5) Partial delivery — whether permitted and at what cost; (6) Title retention (Eigentumsvorbehalt) — seller retains title until full payment; extended retention clauses (verlängerter Eigentumsvorbehalt) cover proceeds and processed goods. Missing acceptance procedure is a HIGH risk — buyer has no recourse for latent defects discovered after deemed acceptance."},
    {"source": "Manufacturing — Liability Cap Best Practice", "text": "Liability limitations in manufacturing supply agreements: Best practice framework: (1) Cap total liability at 100-150% of annual contract value for ordinary negligence; (2) Exclude liability for indirect damages (lost profits, production downtime) unless explicitly agreed; (3) Carve-outs from caps: product liability claims under EU Directive, personal injury, death, gross negligence, fraud; (4) Product recall costs: must be explicitly included if seller is to bear them — courts do not imply recall cost liability; (5) IP infringement: often subject to separate higher cap or unlimited liability; (6) Mutual caps are more commercially balanced and more likely to be enforceable. Under BGB §276, liability for gross negligence (grobe Fahrlässigkeit) cannot be excluded, even in B2B contracts. Insurance requirements should match liability exposure."},
    {"source": "Clause — Warranty in Supply Agreement", "text": "Warranty clause — manufacturing supply agreement: Seller warrants that all products: (a) conform to the agreed specifications; (b) are free from material and workmanship defects for [24 months] from date of delivery; (c) are fit for their intended purpose; (d) are manufactured in compliance with applicable laws including LkSG, REACH, RoHS, CE marking requirements. Seller's liability for warranty claims is limited to: at Seller's option, repair or replacement of defective products, or refund of the purchase price. Warranty does not apply to defects caused by: (i) misuse or improper storage; (ii) unauthorised modification; (iii) normal wear and tear. ALL OTHER WARRANTIES, EXPRESS OR IMPLIED, INCLUDING WARRANTIES OF MERCHANTABILITY, ARE EXCLUDED TO THE EXTENT PERMITTED BY LAW."},

    # ── Litigation / Settlement ────────────────────────────────────────────
    {"source": "ZPO — German Civil Procedure", "text": "Zivilprozessordnung (ZPO) — German Code of Civil Procedure: Key principles: (1) Verhandlungsgrundsatz — parties are responsible for presenting facts; court cannot investigate independently; (2) Beibringungsgrundsatz — each party must produce evidence for its claims; (3) Beweislast (burden of proof) — the party asserting a fact bears the burden of proof; (4) Streitwert — claims value determines court jurisdiction (AG up to €5,000; LG above €5,000) and court fees; (5) Vorläufiger Rechtsschutz — interim relief (einstweilige Verfügung) available within 24-48 hours for urgent cases; (6) Revision — second appeal to BGH (Federal Court of Justice) on points of law only; (7) Enforcement — German judgments are enforceable in EU under Brussels I Regulation (Recast); (8) Statute of limitations under BGB §195: 3 years, starting from end of year in which claim arose and claimant had knowledge."},
    {"source": "Settlement Agreement — Key Clauses", "text": "Settlement agreement (Vergleich/Settlement) essential clauses: (1) Full and final release (Generalquittung) — scope must be precisely defined; overly broad releases covering unknown future claims may be partially void under BGB §138 (contra bonos mores); (2) Confidentiality — prohibits disclosure of settlement amount and terms; carve-outs for legal/tax advisors, regulatory obligations, court filings; (3) No admission of liability — standard clause protecting both parties' public position; (4) Payment terms — amount, currency, payment date, consequences of non-payment (interest at §288 BGB rate: 9% p.a. above base rate for B2B); (5) Dismissal of proceedings — whether with or without prejudice; (6) Costs — each party bears own costs, or cost allocation; (7) Governing law and jurisdiction; (8) Entire agreement — supersedes all prior settlement discussions. Tax treatment of settlement payments should be addressed."},
    {"source": "Arbitration — ICC/DIS Rules", "text": "International arbitration for commercial disputes: ICC Rules (International Chamber of Commerce): filing fee based on amount in dispute; appointment of arbitrator(s); place of arbitration determines applicable procedural law (lex loci arbitri); average duration 2-3 years; advantages: confidentiality, enforceability under New York Convention (160+ countries), party autonomy in arbitrator selection. DIS Rules (Deutsche Institution für Schiedsgerichtsbarkeit): German arbitration institution; proceedings in German or English; seat typically Frankfurt or Munich. Enforcement: New York Convention 1958 — foreign arbitral awards enforceable in 160+ countries without re-litigating merits. Arbitration clauses should specify: institution, number of arbitrators, seat, language. UNCITRAL Model Law governs arbitration in Germany (§§1025-1066 ZPO)."},
    {"source": "Damages — German Contract Law", "text": "Damages in German contract law (Schadensersatz): Under BGB §249, the party causing damage must restore the position that would have existed if the damage-causing event had not occurred (Naturalrestitution). If restoration is impossible or insufficient, money compensation (§251 BGB). Recoverable damages: (1) Direct loss (damnum emergens) — actual financial loss; (2) Lost profit (lucrum cessans) — profit that would have been earned; (3) Consequential damages — production downtime, customer claims passed on to injured party. Non-recoverable without explicit agreement: punitive damages (German law does not recognise punitive damages); pure economic loss without underlying property damage or personal injury (except in specific statutory cases). Mitigation duty (Schadensminderungspflicht) under BGB §254 — injured party must take reasonable steps to mitigate loss; failure to mitigate reduces recoverable damages proportionally."},
    {"source": "Litigation — Release Clause Risk", "text": "Release clause risk analysis in settlement agreements: A broadly drafted release clause may inadvertently release claims the settling party did not intend to give up. Risk factors: (1) 'All claims arising out of or relating to' — courts may interpret broadly to cover unknown claims; (2) Releases signed under duress or with material misrepresentation are voidable; (3) Under BGB §138, a release that is unconscionable (sittenwidrig) is void — e.g., where one party exploits the other's distress to extract an unreasonably broad release for minimal consideration; (4) Future claims — explicitly excluded unless party expressly agrees to release future claims with full awareness; (5) Employee releases — under German law, restrictions on workers' rights (e.g., severance in exchange for waiving unfair dismissal claim) are scrutinised; (6) Best practice: enumerate released claims specifically rather than using omnibus language; (7) Mutual release vs. unilateral release — unilateral releases should reflect higher consideration."},
    {"source": "Injunctions — German Law", "text": "Preliminary injunctions (einstweilige Verfügung) under German law (§§935-945 ZPO): Available for: (1) securing specific performance; (2) regulating the disputed legal relationship (Regelungsverfügung); (3) prohibiting specific conduct. Requirements: (1) Verfügungsanspruch — valid underlying claim; (2) Verfügungsgrund — urgency (Dringlichkeit) — generally presumed if applicant acts within 1 month of becoming aware of the infringement; (3) Proportionality. Ex parte orders possible (without hearing the other side) for IP infringement, unfair competition, and urgent cases. Respondent may apply to set aside (Widerspruch). Risk: if injunction granted wrongly, applicant liable for all damages under §945 ZPO. In employment disputes, injunctions can compel continued employment or prevent dismissal pending main proceedings."},
]

def seed():
    sys.path.insert(0, str(Path(__file__).parent.parent))
    from data_pipeline.vector_store import ingest_document, list_collections

    print(f"Seeding {len(LEGAL_CHUNKS)} legal knowledge chunks into 'legal_knowledge'...")
    full_text = "\n\n".join(f"[{c['source']}]\n{c['text']}" for c in LEGAL_CHUNKS)

    n = ingest_document(full_text, "harveyy_legal_seed.txt", "legal_knowledge", chunk_size=800)
    print(f"✓ Indexed {n} chunks into 'legal_knowledge'")

    cols = list_collections()
    for c in cols:
        print(f"  Collection '{c['name']}': {c['count']} chunks")

if __name__ == "__main__":
    seed()
